name: build
on: [push, pull_request]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "build"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        check-latest: true
    - name: Install deps
      run: npm install
    - name: Build and test
      run: npm run prepare
    - name: Check coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup pages
      uses: actions/configure-pages@v3
    - name: Build pages
      run: |
        cd ./demo-web/
        npm install
        npm run build
        cd ..
        mkdir -p ./pages/demo-web/
        cp -f ./demo-web/index.html ./demo-web/bundle.js ./pages/demo-web/
    - name: Upload page artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './pages/'
    - name: Deploy demo to pages
      id: deployment
      uses: actions/deploy-pages@v2
